service_count_per_node: 1
service_image: registry/service
service_image_tag: "1.0.0"
service_log_level: "INFO"
service_tt_url: "tt_ip"
service_tt_user: "user"
service_tt_pass: "user"
service_base_url: "https://service"
